export const GAME_CONFIG = {
  ANSWER_TIMER_VIDEO: 4,
  PLAY_TIMER_AUDIO_AT: 2,
  INTRO_DELAY_MS: 800,
  NUMBER_OF_QUESTION_IN_SESSION: 50,

  DELAY_LEADERBOARD_MIDGAME: 20000,
  DELAY_SLIDE_LEADERBOARD: 15000
}